### ISSUE TITLE
Contribution: Floppy Disk Texture

### ISSUE THREAD

**Issue by im-hyps** [ascpial/ComputerCreate#3]
I'm using ComputerCreate in my pack, [Soothico](https://www.curseforge.com/minecraft/modpacks/soothico), and I noticed that Floppy Disks are some of the only items not currently supported.
So, I spent some time creating some that fit with Create nicely.

The texture uses the Sturdy Sheet as a base.

How it looks ingame:
![image](https://user-images.githubusercontent.com/30202334/196813944-44ed417a-a6cb-4042-978c-9bb596ede619.png)
![image](https://user-images.githubusercontent.com/30202334/196814018-ce257f25-a174-4795-aadc-51ceec956104.png)
![image](https://user-images.githubusercontent.com/30202334/196814098-f0d88c1b-34e9-4f1c-b4b5-cbe48492de3d.png)

And here is a .zip file with the textures in it.
(Sorry, I don't know how pull requests work for contributions, so I hope putting it in here is okay!)

[FloppyDiskTextures.zip](https://github.com/ascpial/ComputerCreate/files/9824701/FloppyDiskTextures.zip)

**Comment by ascpial** [comment]
Thanks you very much!
I tried to do the texture myself but Im very bad at items.
I will merge that as soon as possible!

**Comment by ascpial** [comment]
I added the textures to the project!
I will update the pack on Modrinth after a rework of the command computer texture!

**Comment by ascpial** [comment]
I released a new version of the pack including your changes : https://github.com/ascpial/ComputerCreate/releases/tag/v0.3

Feel free to update your modpack and client!
