### ISSUE TITLE
Dyed Pocket Computers

### ISSUE THREAD

**Issue by Web7283** [ascpial/ComputerCreate#5]
I noticed that even though turtles can have different colors, if you dye a pocket computer, it will revert back to its original texture.

**Comment by ascpial** [comment]
Thanks for the report!

I added colored pocket computers in v0.5, which is live on [Modrinth](https://modrinth.com/resourcepack/computercreate/version/v0.5) and [Curseforge](https://www.curseforge.com/minecraft/texture-packs/computercreate/files)!
