### ISSUE TITLE
CurseForge Won’t let me add it to my modpack

### ISSUE THREAD

**Issue by OctoMango** [ascpial/ComputerCreate#8]
I have a 1.20.1 mod pack and cents CurseForge doesn’t like it when you try to add resource packs that aren’t for your version even if they work fine. The resource pack works fine on 1.20.1 but could you please upload the 1.20 version labeled as 1.20.1, i would really like to have this in my modpack

**Comment by ascpial** [comment]
I updated the labels on the latest version: https://www.curseforge.com/minecraft/texture-packs/computercreate/files/5643693

I will probably fix the auto upload as well as change older versions.

**Comment by OctoMango** [comment]
Thank you so much 🙏
